# Generated by Django 3.1.3 on 2020-11-20 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('classes', models.CharField(max_length=100)),
                ('subject', models.CharField(default='N/A', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('quality', models.CharField(choices=[('New', 'New'), ('LUsed', 'Lightly Used'), ('Used', 'Used'), ('Damaged', 'Damaged')], default='Used', max_length=100)),
                ('status', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Inactive', 'Inactive')], default='Inactive', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
