# Generated by Django 3.1.3 on 2020-11-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyorsell', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='auction.book')),
            ],
        ),
    ]
