# Generated by Django 3.1.3 on 2020-11-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
