# Generated by Django 3.1.3 on 2020-11-20 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0004_auto_20201120_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('quality', models.CharField(choices=[('New', 'New'), ('LUsed', 'Lightly Used'), ('Used', 'Used'), ('Damaged', 'Damaged')], default='Used', max_length=100)),
                ('status', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Inactive', 'Inactive')], default='Inactive', max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='auction.book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookInstance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='auction.bookinstance'),
        ),
    ]
