# Generated by Django 3.1.3 on 2020-11-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyorsell',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Bell')], max_length=50),
        ),
    ]
