# Generated by Django 3.1.3 on 2020-11-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auto_20201121_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyorsell',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=50),
        ),
    ]
