# Generated by Django 3.1.3 on 2020-11-21 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0009_auto_20201121_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Order_Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
