# Generated by Django 3.1.3 on 2020-11-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20201121_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyorsell',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=50),
        ),
    ]
