# Generated by Django 3.1.3 on 2021-04-29 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auto_20210319_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 20, 6, 33, 188237, tzinfo=utc)),
        ),
    ]
