# Generated by Django 3.1.3 on 2020-11-28 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmessages', '0002_conversation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reason',
        ),
        migrations.AddField(
            model_name='conversation',
            name='reason',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
